[package]

name = "monoid"
version = "0.0.4"
authors = ["Igor Polyakov <iopguy@gmail.com>"]
description = "A package providing some common monoids for use in Rust"
repository = "https://github.com/iopq/monoid"
license = "MIT"
