[package]
authors = ["Igor Polyakov <iopguy@gmail.com>"]
description = "A package providing some common monoids for use in Rust"
license = "MIT"
name = "monoid"
repository = "https://github.com/iopq/monoid"
version = "0.0.5"

[dependencies]
bencher = "*"

[[bench]]
name = "benches"
harness = false
